from __future__ import annotations

from pathlib import Path

import pandas as pd
import streamlit as st

from rs_stages.data import download_yfinance_history
from rs_stages.quant import ma_30w_series

st.set_page_config(page_title="RS-Stages", page_icon="RS", layout="wide", initial_sidebar_state="collapsed")
st.set_option("client.toolbarMode", "minimal")

RESEARCH_PATH = Path("data/latest_research.csv")
UNIVERSE_PATH = Path("data/ind_niftytotalmarket_list.csv")

st.markdown("""
<style>
:root { color-scheme: light; }
.stApp { background:#fff; }
.block-container { max-width:1480px; padding:1.8rem 3rem 3rem; }
[data-testid="stHeader"] { background:#fff; }
[data-testid="stSidebar"] { display:none; }
[data-testid="stMetric"] { background:#fff; border:1px solid #e7e9ee; border-radius:8px; padding:.8rem .9rem; box-shadow:none; }
[data-testid="stMetricValue"] { font-size:1.35rem; font-weight:650; letter-spacing:-.03em; }
[data-testid="stMetricLabel"] { color:#6b7280; font-size:.7rem; text-transform:uppercase; letter-spacing:.07em; }
.stTabs [data-baseweb="tab-list"] { gap:1.35rem; border-bottom:1px solid #e7e9ee; }
.stTabs [data-baseweb="tab"] { height:2.8rem; padding:0 .05rem; color:#667085; font-weight:520; }
.stTabs [aria-selected="true"] { color:#111827; }
[data-testid="stDataFrame"] { border:1px solid #e7e9ee; border-radius:8px; overflow:hidden; }
.rs-eyebrow { color:#7a8494; font-size:.68rem; font-weight:650; letter-spacing:.12em; text-transform:uppercase; margin-bottom:.35rem; }
.rs-title { color:#111827; font-size:2.35rem; font-weight:680; letter-spacing:-.05em; line-height:1.02; margin:0; }
.rs-subtitle { color:#667085; font-size:.95rem; line-height:1.55; max-width:760px; margin:.55rem 0 1.35rem; }
.rs-section { color:#111827; font-size:1rem; font-weight:650; letter-spacing:-.015em; margin:1.35rem 0 .5rem; }
.rs-note { color:#7a8494; font-size:.78rem; line-height:1.45; }
.rs-status { display:inline-block; color:#52606d; background:#f6f7f9; border:1px solid #e7e9ee; border-radius:999px; padding:.3rem .65rem; font-size:.72rem; }
@media (max-width: 700px) {
  .block-container { padding:1.1rem 1rem 2rem; }
  .rs-title { font-size:2rem; }
  .rs-subtitle { font-size:.9rem; margin-bottom:1rem; }
  .stTabs [data-baseweb="tab-list"] { gap:.85rem; overflow-x:auto; }
  .stTabs [data-baseweb="tab"] { font-size:.82rem; }
}
</style>
""", unsafe_allow_html=True)


@st.cache_data(ttl=3600, show_spinner=False)
def load_research() -> pd.DataFrame:
    if not RESEARCH_PATH.exists():
        raise FileNotFoundError("The validated research snapshot has not been published yet.")
    frame = pd.read_csv(RESEARCH_PATH)
    if "Symbol" not in frame.columns:
        raise ValueError("Research snapshot is missing Symbol")
    frame["Symbol"] = frame["Symbol"].astype(str).str.strip()
    return frame.set_index("Symbol")


@st.cache_data(ttl=3600, show_spinner=False)
def load_stock_history(symbol: str, end_date: str) -> pd.DataFrame:
    return download_yfinance_history(symbol, start=pd.Timestamp(end_date) - pd.Timedelta(days=550), end=pd.Timestamp(end_date) + pd.Timedelta(days=1))


def stage_name(value: object) -> str:
    if not isinstance(value, str):
        return "Unknown"
    return value.replace("Stage 1 — Basing", "Stage 1").replace("Stage 2 — Advancing", "Stage 2").replace("Stage 3 — Topping", "Stage 3").replace("Stage 4 — Declining", "Stage 4")


st.markdown('<div class="rs-eyebrow">Nifty Total Market · Quantitative Research Platform</div>', unsafe_allow_html=True)
st.markdown('<div class="rs-title">RS-Stages</div>', unsafe_allow_html=True)
st.markdown('<div class="rs-subtitle">Relative strength, market stages, breakouts and industry breadth — presented from the latest independently reconciled research snapshot.</div>', unsafe_allow_html=True)

try:
    result = load_research()
except Exception as exc:
    st.error("Research snapshot unavailable")
    st.caption(str(exc))
    st.info("The production snapshot is generated by the real-data audit workflow. No file upload or manual data entry is required.")
    st.stop()

source_universe = pd.read_csv(UNIVERSE_PATH) if UNIVERSE_PATH.exists() else pd.DataFrame()
dummy_count = int(source_universe["Symbol"].astype(str).str.startswith("DUMMY", na=False).sum()) if "Symbol" in source_universe.columns else 0
valid_rs = result["RS_Score"].notna() if "RS_Score" in result else pd.Series(False, index=result.index)
latest = pd.to_datetime(result["Date"], errors="coerce").dropna().max() if "Date" in result else pd.NaT

home, ranking, industry_tab, stock_tab, methodology = st.tabs(["Dashboard", "RS Ranking", "Industry", "Stock", "Methodology"])

with home:
    st.markdown('<span class="rs-status">Validated research snapshot</span>', unsafe_allow_html=True)
    st.markdown(f'<div class="rs-note" style="margin-top:.45rem">Information boundary · {latest.date().isoformat() if pd.notna(latest) else "—"} · latest completed NSE session</div>', unsafe_allow_html=True)
    st.markdown('<div class="rs-section">Market overview</div>', unsafe_allow_html=True)
    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Source universe", f"{len(source_universe):,}")
    c2.metric("Acquisition universe", f"{len(result):,}")
    c3.metric("Valid RS", f"{int(valid_rs.sum()):,}")
    c4.metric("Breakouts", f"{int(result['Breakout'].sum()):,}")
    c5.metric("Confirmed", f"{int(result['Breakout_Confirmed'].sum()):,}")

    left, right = st.columns([.85, 1.35])
    with left:
        st.markdown('<div class="rs-section">Stage distribution</div>', unsafe_allow_html=True)
        stage_counts = result["Stage"].map(stage_name).value_counts().reindex(["Stage 1", "Stage 2", "Stage 3", "Stage 4", "Unknown"], fill_value=0)
        st.bar_chart(stage_counts, height=270)
    with right:
        st.markdown('<div class="rs-section">Strongest relative strength</div>', unsafe_allow_html=True)
        cols = ["Industry", "RS_Score", "RS_Blend", "Stage", "Near_52W_High", "Breakout", "Breakout_Confirmed"]
        st.dataframe(result.loc[valid_rs].sort_values("RS_Score", ascending=False).head(12)[cols], use_container_width=True, hide_index=False, height=270)

    st.markdown('<div class="rs-section">Market and data status</div>', unsafe_allow_html=True)
    s1, s2, s3, s4, s5 = st.columns(5)
    s1.metric("Industries", f"{result['Industry'].nunique():,}")
    s2.metric("Latest session", latest.date().isoformat() if pd.notna(latest) else "—")
    s3.metric("Liquid > ₹5Cr", f"{int(result['Liquid_UI_Filter'].sum()):,}")
    s4.metric("Near 52W high", f"{int(result['Near_52W_High'].sum()):,}")
    s5.metric("DUMMY excluded", f"{dummy_count:,}")

with ranking:
    st.markdown('<div class="rs-section">Cross-sectional RS ranking</div>', unsafe_allow_html=True)
    st.markdown('<div class="rs-note">The displayed ranking is the validated research output. Filters change presentation only.</div>', unsafe_allow_html=True)
    f1, f2, f3, f4 = st.columns(4)
    industries = ["All"] + sorted(result["Industry"].dropna().unique().tolist())
    selected_industry = f1.selectbox("Industry", industries)
    selected_stage = f2.selectbox("Stage", ["All", "Stage 1", "Stage 2", "Stage 3", "Stage 4"])
    min_rs = f3.number_input("Minimum RS Score", min_value=1, max_value=99, value=1, step=1)
    liquid_only = f4.checkbox("Liquid only", value=False)
    search = st.text_input("Search symbol", placeholder="Search NSE symbol")
    view = result.copy()
    if selected_industry != "All": view = view[view["Industry"] == selected_industry]
    if selected_stage != "All": view = view[view["Stage"].map(stage_name) == selected_stage]
    view = view[view["RS_Score"].fillna(0) >= min_rs]
    if liquid_only: view = view[view["Liquid_UI_Filter"]]
    if search: view = view[view.index.astype(str).str.contains(search.strip(), case=False, regex=False)]
    display_cols = ["Industry", "Date", "RS_Score", "RS_Blend", "R3M", "R6M", "R9M", "R12M", "Stage", "MA_30W", "MA_30W_Slope_10S_Pct", "Near_52W_High", "Volume_Ratio", "U_D", "AvgValue20", "Breakout", "Breakout_Confirmed"]
    st.markdown(f'<div class="rs-note">{len(view):,} stocks shown</div>', unsafe_allow_html=True)
    st.dataframe(view.sort_values(["RS_Score", "RS_Blend"], ascending=False)[display_cols], use_container_width=True, height=650, hide_index=False)

with industry_tab:
    st.markdown('<div class="rs-section">Industry breadth</div>', unsafe_allow_html=True)
    st.markdown('<div class="rs-note">Exact NSE CSV Industry classification. No remapping or sector consolidation.</div>', unsafe_allow_html=True)
    industry_summary = result.groupby("Industry", dropna=False).agg(Stocks=("RS_Score", "size"), Valid_RS=("RS_Score", "count"), Median_RS=("RS_Score", "median"), Stage_2=("Stage", lambda s: (s == "Stage 2 — Advancing").sum()), Stage_4=("Stage", lambda s: (s == "Stage 4 — Declining").sum()), Breakouts=("Breakout", "sum"), Confirmed=("Breakout_Confirmed", "sum")).sort_values("Median_RS", ascending=False)
    st.dataframe(industry_summary, use_container_width=True, height=600)
    st.markdown('<div class="rs-section">Top industry median RS</div>', unsafe_allow_html=True)
    st.bar_chart(industry_summary.head(20)["Median_RS"], height=300)

with stock_tab:
    st.markdown('<div class="rs-section">Stock detail</div>', unsafe_allow_html=True)
    selected_symbol = st.selectbox("Select stock", sorted(result.index.astype(str).tolist()))
    row = result.loc[selected_symbol]
    m1, m2, m3, m4, m5 = st.columns(5)
    m1.metric("RS Score", "—" if pd.isna(row["RS_Score"]) else f"{int(row['RS_Score'])}")
    m2.metric("Stage", stage_name(row["Stage"]))
    m3.metric("RS Blend", "—" if pd.isna(row["RS_Blend"]) else f"{row['RS_Blend']:.2%}")
    m4.metric("Volume Ratio", "—" if pd.isna(row["Volume_Ratio"]) else f"{row['Volume_Ratio']:.2f}×")
    m5.metric("U/D", "—" if pd.isna(row["U_D"]) else f"{row['U_D']:.2f}")
    st.markdown(f"**{selected_symbol}** · {row['Industry']} · {pd.Timestamp(row['Date']).date()}")
    try:
        history = load_stock_history(selected_symbol, str(pd.Timestamp(row["Date"]).date()))
        chart = history[["Close"]].copy()
        chart["MA_30W"] = ma_30w_series(chart["Close"])
        st.line_chart(chart.tail(220), height=340)
    except Exception as exc:
        st.caption(f"Price history unavailable for this stock: {exc}")
    detail = pd.DataFrame({"Metric": ["R3M", "R6M", "R9M", "R12M", "MA_30W", "MA_30W slope (10S)", "52W High", "Near 52W High", "AvgValue20", "Breakout", "Breakout Confirmed"], "Value": [row.get("R3M"), row.get("R6M"), row.get("R9M"), row.get("R12M"), row.get("MA_30W"), row.get("MA_30W_Slope_10S_Pct"), row.get("High_52W"), row.get("Near_52W_High"), row.get("AvgValue20"), row.get("Breakout"), row.get("Breakout_Confirmed")]})
    st.dataframe(detail, use_container_width=True, hide_index=True)

with methodology:
    st.markdown('<div class="rs-section">Locked methodology</div>', unsafe_allow_html=True)
    st.markdown("**Universe** — Official Nifty Total Market constituent CSV. Industry is exactly the NSE CSV `Industry` field. No F&O filtering or sector remapping.\n\n**Relative Strength** — 3/6/9/12 calendar-month returns using the last available NSE session on or before each reference date. Blend = 40% / 20% / 20% / 20%. RS Score = `rank(pct=True, method='min') × 98 + 1`, rounded.\n\n**Stage** — 30-calendar-week simple moving average and the locked Close-vs-MA / slope truth table.\n\n**Breakout** — locked Stage 2 + 52-week high proximity + volume confirmation rules.\n\n**Liquidity** — 20 completed sessions of Close × raw Volume with the locked threshold. It does not alter RS ranking.\n\n**Information boundary** — only completed NSE sessions available before the decision boundary are used.")
    st.caption("Production dashboard data is published only after the independent real-data reconciliation passes.")
